### ISSUE TITLE
TS2305: Module  "awesome-logging"  has no exported member  AwesomeLogger

### ISSUE THREAD

**Issue by cdwmhcc** [LoaderB0T/awesome-logging#138]
![image](https://github.com/LoaderB0T/awesome-logging/assets/8030134/b05b96a9-f32e-4ca1-bcc0-c60ae6daa79b)

**Comment by LoaderB0T** [comment]
Hi, I can't seem to reproduce this. Which version are you using?

With 1.1.2 it works as expected:
![image](https://github.com/LoaderB0T/awesome-logging/assets/37637338/3cff6b8f-749a-4d31-8d42-de614a0b3ea8)

**Comment by cdwmhcc** [comment]
WebStorm: 2023.2.3
NodeJS: 20.9.0
awesome-logging: 1.1.2

**Comment by LoaderB0T** [comment]
Strange. I never tested with webstorm, so maybe that's an issue...
Are there any exports at all? What happens when you go to the definition of "awesome-logging"? Does it find an index.d.td or something?

**Comment by LoaderB0T** [comment]
Which typescript version are you using?

**Comment by cdwmhcc** [comment]
``` json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "node16",
    "lib": ["ESNext", "DOM"],
    "moduleResolution": "node16",
    "rootDir": "src",
    "outDir": "dist",
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "alwaysStrict": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "useDefineForClassFields": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "strictNullChecks": false,
    "baseUrl": "src",
    "types": ["node"],
    "paths": {
      "@": [".."],
      "@/*": ["../*"],
      "#hooks": ["./_hooks/index.js"],
      "#hooks/*": ["./_hooks/*"],
      "#utils": ["./_utils/index.js"],
      "#utils/*": ["./_utils/*"],
      "#config": ["./_utils/config.js"],
      "#api": ["./api/index.js"],
      "#api/*": ["./api/*"],
      "#types": ["./types/index.js"],
      "#types/*": ["./types/*"],
      "cheerio": ["../node_modules/cheerio/lib/index.d.js"]
    }
  },
  "include": ["./src/**/*"],
  "exclude": ["../node_modules"]
}
```

typescript: 5.2.2

This is the problem:

TS2835: Relative import paths need explicit file extensions in EcmaScript imports when  --moduleResolution  is  node16  or  nodenext . Did you mean  ./awesome-logger.js ?

![image](https://github.com/LoaderB0T/awesome-logging/assets/8030134/ff472b11-8325-4473-beb9-2cd7805bf3d2)

**Comment by cdwmhcc** [comment]
When using `nodenext` or `node16` you need to introduce the `.js` extension. Ha ha

**Comment by LoaderB0T** [comment]
Well, I am. See if you open the js files, all extensions are there... The file you saw is the .d.ts file, is it not?
I am not sure if extensions are required in the .d.ts files

**Comment by LoaderB0T** [comment]
Also the second entry './logger' is a folder containing index files, so the error must be something else... I will try with webstorm.

Can you provide me with a repro scenario? E.g. on stackblitz or so? I will see whether I can reproduce it on my side, but so far no luck.

**Comment by cdwmhcc** [comment]
You don't understand that when --moduleResolution is node16 or nodenext in the tsconfig.json configuration file, the imported js/ts file must have a .js extension and cannot be omitted.

It is recommended not to omit the .js suffix. In fact, omitting the suffix does not comply with the specification.

**Comment by cdwmhcc** [comment]
> Relative import paths need explicit file extensions in EcmaScript imports when  --moduleResolution  is  node16  or  nodenext

https://github.com/microsoft/TypeScript/issues/49083

**Comment by LoaderB0T** [comment]
Yes, you are right, I misread the output files. However, the ".js" extension is omitted even if I write it in the source...
I will check and get back to you.

**Comment by LoaderB0T** [comment]
Can you check again with version 1.2.3?

**Comment by LoaderB0T** [comment]
I missed some places where the .js extension was missing, I think I got all of them now. Sorry for that & thanks a lot for reporting this issue.

**Comment by cdwmhcc** [comment]
![image](https://github.com/LoaderB0T/awesome-logging/assets/8030134/d814e422-5bd4-402b-a4d9-148caa4f8d6d)

**Comment by cdwmhcc** [comment]
![image](https://github.com/LoaderB0T/awesome-logging/assets/8030134/15a52e7a-936a-4d10-8cc0-21f4ebb4f5b3)

**Comment by LoaderB0T** [comment]
Omg. My Bad. Gimme a sec.

**Comment by LoaderB0T** [comment]
Try again with 1.1.4. I am sorry. I recently did some changes to the tsconfig which I never published. Those changes resultet in a misconfigured path. Now it should be working again.

**Comment by cdwmhcc** [comment]
![image](https://github.com/LoaderB0T/awesome-logging/assets/8030134/7c50e52e-2a79-4ebf-9239-e87cff5a9a6e)
1.1.4 Great job, thank you for your work!

**Comment by LoaderB0T** [comment]
Thank you so much. If you have any questions or feedback, please let me know :)
Also, I am excited to see what you are going to use it for, so also feel free to share anything :)

**Comment by cdwmhcc** [comment]
> Thank you so much. If you have any questions or feedback, please let me know :) Also, I am excited to see what you are going to use it for, so also feel free to share anything :)

https://listr2.kilic.dev/

I'm currently using it. You can refer to this.

**Comment by cdwmhcc** [comment]
I am making an automatic packaging dmg tool for macOS. Haha
